### PR TITLE
Add support for "double" alias of float

### PR DESCRIPTION
**Pull request by nsrosenqvist**
Very simple change, just added support for casting floats using the type name "double" in the `cast` method. See issue https://github.com/jrfnl/PHP-cast-to-type/issues/16.

### CODE REVIEW

**Review by jrfnl — COMMENTED** [review]
Valid point and happy to accept this change.

For the record: the indentation in the `class.cast-to-type-php4.php` file looks off. Then again - is anyone still using PHP 4 ? I may as well drop support for PHP 4 by now.

**Comment by jrfnl** [comment]
I've done a quick update of the (very outdated) CI. Would you mind rebasing and fixing that spacing issue ? After that I'll merge this fix & release it.

**Comment by nsrosenqvist** [comment]
Sorry about that, my editor had switched back to spaces when I edited the second file. Should be good now. The PR shouldn't need a rebase since there are no conflicts with the branch, should it?

**Comment by jrfnl** [comment]
> Sorry about that, my editor had switched back to spaces when I edited the second file. Should be good now.

Thanks for doing that!

> The PR shouldn't need a rebase since there are no conflicts with the branch, should it?

Not with the extra commit (the old CI was on Travis, now it is on GH Actions and it does need to run before merging, with the extra commit I was able to tell it to do so.)

**Pull request merged**
